- arguments: [--color=auto]

- group:
    name: default
    enabled: true

# Ignore specific hints if needed
# - ignore: {name: "Use camelCase"}
# - ignore: {name: "Redundant bracket"}

# Custom hints
# - warn: {lhs: "map f (map g x)", rhs: "map (f . g) x"}
